### ISSUE TITLE
Unncessary .DS_Store files left behind from Mac file system

### ISSUE THREAD

**Issue by damienwebdev** [kristenbaldwin/Javascript-Exercises#1]
Add a `.gitignore` to the project and clear out these awful files.

https://git-scm.com/docs/gitignore

**Comment by kristenbaldwin** [comment]
Thanks 👍. I just add the pathname to the .gitignore, correct?

**Comment by damienwebdev** [comment]
Correct, that will work for all NEW files, but you'll have to retroactively delete all existing ones from the project as well. See that https://github.com/kristenbaldwin/Javascript-Exercises/blob/master/blackjack/.DS_Store still exists.

**Comment by damienwebdev** [comment]
Looks like you finished this. Closing it.

**Comment by kristenbaldwin** [comment]
Thanks, Damien! I'll make sure to go through my other repos and always add a .gitignore.
